### ISSUE TITLE
App crashes when trying to download update

### ISSUE THREAD

**Issue by dominik-muc** [Evolution-X/packages_apps_Updates#56]
**Package version: 2.0.0 on Android 14**

msg: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{23f9de4 14493:org.evolution.ota/u0a358} targetSDK=34
stacktrace: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{23f9de4 14493:org.evolution.ota/u0a358} targetSDK=34
    at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
    at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
    at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
    at android.os.Parcel.readParcelable(Parcel.java:4852)
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
    at android.os.Parcel.createException(Parcel.java:3041)
    at android.os.Parcel.readException(Parcel.java:3024)
    at android.os.Parcel.readException(Parcel.java:2966)
    at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6796)
    at android.app.Service.startForeground(Service.java:775)
    at org.evolution.ota.controller.UpdaterService.handleUpdateStatusChange(UpdaterService.java:253)
    at org.evolution.ota.controller.UpdaterService.-$$Nest$mhandleUpdateStatusChange(UpdaterService.java:0)
    at org.evolution.ota.controller.UpdaterService$1.onReceive(UpdaterService.java:107)
    at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:319)
    at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:127)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8173)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by joeyhuab** [comment]
Addressed with https://github.com/Evolution-X/packages_apps_Updates/commit/3a4162f9bde470b8ba8fa00dead3cb05d1e14e5d
